### ISSUE TITLE
3주차 미션 리뷰입니다.

### ISSUE THREAD

**Issue by sonypark** [sanhee/codesquad-cocoa-java#2]
안녕하세요 노을, 소니입니다.
3주차 미션에 대해 간단한 피드백 남기니 참고해주세요 :)

1. 하나의 클래스에 모든 로직을 다 작성하는 건 가독성과 코드의 재사용성면에서 좋지 않습니다. 역할별로 클래스르 구분하고 필요한 클래스를 import 해서 사용하는 방식으로 변경해보세요

2. 사용하지 않는 코드는 주석으로 해놓지 말고 삭제해주세요.

3. 모든 메서드가 static 메서드인데 이렇게 구현할 경우 어떤 장단점이 있는지 공부해보세요.

4. 메서드명은 동사로 작성하고 카멜케이스로 작성합니다. 이 규칙이 지켜지지 않은 메서드가 보이네요. 또한  모든 네이밍은 약어를 최대한 사용하지 않고 작성하는게 좋습니다. 약어는 본인만 알아볼 수 있는 경우가 많아 다른 사람이 이해하기 어려울 수 있습니다. (ex. chHourToKor)

5. Enum에 대해 공부해보시고 구현 로직에 적용할만한 부분이 있는지 생각해보세요. 🧐

**Comment by sanhee** [comment]
안녕하세요 소니 피드백 감사합니다.
한가지 질문이 있는데 한글시계로 구현을 할 때, 2차원 배열이 아닌 ArrayList로  해도 큰 차이나 문제가 없는 걸까요??
